modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"
issueTrackerURL="https://github.com/wratixor/backstick/issues"

[[mods]]
modId="backstick"
version="${file.jarVersion}"
displayName="BackStick"
displayURL="https://www.curseforge.com/minecraft/mc-mods/backstick"
logoFile="logo.png"
credits="Thanks you!"
authors="Wratixor"
#displayTest="MATCH_VERSION"
description='''
BackStick (named after backslash) contains:
- 4 new items for crafting (BackStick, BackBreacker, BackMutator, BackGravier);
- 7 levels of development for each (wood, stone, copper, iron, gold, diamond, netherite);
- as well as several recipes that make life easier using it all.
Source - https://github.com/wratixor/backstick
'''

[[dependencies.backstick]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.backstick]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
